[project]
name = "2048"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "numba>=0.62.1",
    "numpy>=2.3.4",
    "pygame>=2.6.1",
    "requests>=2.32.5",
]
